# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_post_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.CharField(choices=[('Docs', 'Документы'), ('Events', 'События'), ('Announce', 'Анонсы'), ('Links', 'Ссылки')], default='Docs', max_length=10, verbose_name='Раздел'),
        ),
    ]
