# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20170602_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='published_date',
        ),
    ]
