# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-03 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20170602_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activitie',
            new_name='Activities',
        ),
        migrations.RenameModel(
            old_name='New',
            new_name='News',
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
    ]
